### ISSUE TITLE
ERROR curl 'https://www.archimatetool.com/downloads/

### ISSUE THREAD

**Issue by 1795455** [abes-esr/archi-htmlreport-docker#13]
Hello, I am a junior developer and I find an error when I try to build the image, maybe it is a mistake on my part, but I see an issue related here.
 
 => ERROR [ 3/12] RUN curl 'https://www.archimatetool.com/downloads/'  

I also find it difficult to connect a repository with bitbucket, the way I see it, the SSH keys are correct, and the chmod too, I'm running the code via WSL 2, any suggestions? 

-> SSH key found for git clone (.ssh/id_rsa is ready)
-> Git clone of archimatetool model repository: git@bitbucket.org:hruizmar/caa1795455.git
Cloning into '/archi-model-git-repo'...
-> Running the create-htmlreport.prescript.sh script.
-> Generating HTML report from the archimatetool model.

java.io.IOException: Model was not loaded
        at com.archimatetool.reports.commandline.HTMLReportProvider.run(HTMLReportProvider.java:66)
        at com.archimatetool.commandline.CentralScrutinizer.runProviderOptions(CentralScrutinizer.java:164)
        at com.archimatetool.commandline.CentralScrutinizer.start(CentralScrutinizer.java:82)
        at org.eclipse.equinox.internal.app.Ec

2023/02/17 00:12:14 [error] 21#21: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"

Thank you!

**Comment by benjamin-feron** [comment]
Hello, I think if you use the latest version, your problem will disappear.
