### ISSUE TITLE
Bump to archi 5.2.0

### ISSUE THREAD

**Issue by janesser** [abes-esr/archi-htmlreport-docker#15]
Salut,

this is a great container to host archi-htmlreport. We are about to drop the "work-around" we've been with until now.

BTW would you mind a PR bumping to archi 5.2.0? 
thus (probably not just for us) relevant improvement about htmlexport would be included.

BR,
Jan

**Comment by aurelien23** [comment]
Thank you very much !

I just accepted your PR.

I will change the nginx tag, to the latest stable release (1.25.3).

Best regards,
Aurélien
