### ISSUE TITLE
Integrate with github pages

### ISSUE THREAD

**Issue by fglaeser** [abes-esr/archi-htmlreport-docker#8]
Hi I would like to use the docker image just to build the html site an then push to my gh-pages branch (I'm using github pages to host the html site), also I would like to run this in a Github Action to re-generate the html site every time I push some changes to the repo. Any suggestions?

Thank in advanced

**Comment by kerphi** [comment]
Hello,

Thanks for your interest.
I suggest to look at this part of the code: https://github.com/abes-esr/archi-htmlreport-docker/blob/master/create-htmlreport.periodically.sh#L34-L39
This is the "magic command" to generate the HTML website thanks to the "Archi" headless command.
Then try to push it some way to your github-pages.

Good luck.
